# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget hyperfox)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target hyperfox
add_library(hyperfox SHARED IMPORTED)

set_target_properties(hyperfox PROPERTIES
  INTERFACE_LINK_LIBRARIES "MPI::MPI_CXX;/home/jfausty/workspace/Dependencies/petsc-3.13.2/arch-linux-c-debug/lib/libpetsc.so;/usr/lib/x86_64-linux-gnu/liblapack.so;/usr/lib/x86_64-linux-gnu/libblas.so;/usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_usempif08.so;/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_usempi_ignore_tkr.so;/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_mpifh.so;/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so;/usr/lib/gcc/x86_64-linux-gnu/7/libgfortran.so;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/gcc/x86_64-linux-gnu/7/libgcc_s.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/gcc/x86_64-linux-gnu/7/libquadmath.so;/usr/lib/gcc/x86_64-linux-gnu/7/libstdc++.so;/usr/lib/x86_64-linux-gnu/libdl.so;Eigen3::Eigen;-L/home/jfausty/workspace/Dependencies/moab/install/MOAB/lib -lMOAB -L/home/jfausty/workspace/Dependencies/hdf5-1.12.0/hdf5/lib      -lhdf5_hl  -lz -lhdf5       -lopenblas  -lopenblas  -ldl -lz -lm -lm -lm;hdf5;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so;Boost::filesystem;/home/jfausty/workspace/Dependencies/Zoltan_v3.83/build/lib/libzoltan.a"
)

# Import target "hyperfox" for configuration "Release"
set_property(TARGET hyperfox APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(hyperfox PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/jfausty/workspace/Codes/HyperFox/parbuild/lib/libhyperfox.so"
  IMPORTED_SONAME_RELEASE "libhyperfox.so"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
